name: Daily MarkSix JSON Fetch

on:
  schedule:
    - cron: '30 14 * * *'     # UTC14:30 = 台北22:30
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - run: pip install requests

    - run: python 30marksix_crawler.py

    - run: |
        mkdir -p public
        mv marksix_last30.json public/marksix_last30.json
        touch public/.nojekyll

    - uses: actions/configure-pages@v3

    - uses: actions/upload-pages-artifact@v1
      with:
        path: public

    - uses: actions/deploy-pages@v1
