# .github/workflows/deploy-pages.yml

# ── 1️⃣ 最顶层统一设定权限，保证 pages-build-deployment 能下载所需 Actions
permissions:
  contents: read         # 允许读代码仓库
  pages: write           # 允许部署 GitHub Pages
  id-token: write        # 允许 OIDC 登录

name: Daily MarkSix JSON Fetch

on:
  schedule:
    - cron: '30 14 * * *'    # UTC14:30 = 台北22:30
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run crawler → output JSON
        run: python 30marksix_crawler.py

      - name: Prepare public directory
        run: |
          rm -rf public
          mkdir public
          mv marksix_last30.json public/marksix_last30.json
          touch public/.nojekyll

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
