name: Build & Deploy MarkSix JSON

on:
  schedule:
    # 每天 UTC 14:30 = Asia/Taipei 22:30
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run crawler → output JSON
      run: python 30marksix_crawler.py

    - name: Prepare output for Pages
      run: |
        mkdir public
        mv marksix_last30.json public/marksix.json
        # 禁用 Jekyll
        touch public/.nojekyll

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: public

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
